[browser]
# Set your desired browser tab title
pageTitle = "KL Competitor Heatmap"

# Set the path to your favicon (assuming it's in the same directory as 
your Streamlit script)
favicon = "yogaicon.ico"
